apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-label
  labels:
    team: frontend
    version: "1.0"
    environment: production
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
